jq1:
	cat tmpl_open.html tmpl_jquery_1.html tmpl_close.html > test_jquery_1.html

jq2:
	cat tmpl_open.html tmpl_jquery_2.html tmpl_close.html > test_jquery_2.html

get1:
	curl https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js > tmpl_jquery_1.html

get2:
	curl https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js > tmpl_jquery_2.html